# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_place_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name '),
        ),
    ]
