# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-19 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20180619_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='adress',
            field=models.CharField(default=datetime.datetime(2018, 6, 19, 11, 55, 22, 126742), max_length=100, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f '),
        ),
    ]
